### ISSUE TITLE
Compilation failed after upgrading yarp

### ISSUE THREAD

**Issue by S-Dafarra** [robotology-playground/yarp-matlab-bindings#12]
I was attempting to compile after upgrading ``yarp``, without success. I attach here the full log since the errors are many.
[log.txt](https://github.com/robotology-playground/yarp-matlab-bindings/files/1274588/log.txt)

**Comment by traversaro** [comment]
On which branch do you have `YARP`? On which branch do you have `yarp-matlab-bindings`?

**Comment by S-Dafarra** [comment]
Both devel

**Comment by traversaro** [comment]
Can you try to update after https://github.com/robotology-playground/yarp-matlab-bindings/commit/07600ea41cc05795efdd4c37d53a7907c49e28b7 ?

**Comment by S-Dafarra** [comment]
It did the job, thanks a lot!
