### ISSUE TITLE
Errors while compiling with YARP_USES_MATLAB=ON if YARP is compiled with YARP_WRAP_STL_STRING set to OFF

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/yarp-matlab-bindings#15]
I tried to compile the `devel` branch of this repo. I got the following error:

```
gnava@iitiicubws039:~/Software/gitHub/robotology/codyco-superbuild/build/libraries/yarp-matlab-bindings (master)$ make
[ 50%] Building CXX object matlab/CMakeFiles/yarpMEX.dir/autogenerated/yarpMATLAB_wrap.cxx.o
/home/gnava/Software/gitHub/robotology/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/autogenerated/yarpMATLAB_wrap.cxx: In function ‘int _wrap_plus__SWIG_0(int, mxArray**, int, mxArray**)’:
/home/gnava/Software/gitHub/robotology/codyco-superbuild/libraries/yarp-matlab-bindings/matlab/autogenerated/yarpMATLAB_wrap.cxx:4954:12: error: ‘operator+’ is not a member of ‘yarp::os’
   result = yarp::os::operator +((yarp::os::ConstString const &)*arg1,(yarp::os:
```

**Comment by gabrielenava** [comment]
similar to https://github.com/robotology-playground/yarp-matlab-bindings/issues/14

**Comment by traversaro** [comment]
Unable to reproduce on my machine, are you using the branch `devel` of both YARP and yarp-matlab-bindings ?

**Comment by gabrielenava** [comment]
Yes I'm in `devel` in both repos. I have everything installed using `codyco-superbuild`.

**Comment by traversaro** [comment]
Quick fix: set the YARP cmake configuration variable `YARP_WRAP_STL_STRING` to `ON`. The default for this variable has been changed in https://github.com/robotology/yarp/pull/1406 .

**Comment by traversaro** [comment]
I could push the bindings that work with `YARP_WRAP_STL_STRING` to `OFF`, but this would break the compilation for all the users that still have `YARP_WRAP_STL_STRING` set to `ON` in their cache. : (

**Comment by gabrielenava** [comment]
It is compiling, so this workaround fixed the issue for now.

**Comment by traversaro** [comment]
@drdanz This is a bit of an edge case, and probably is not worth changing the decision taken for YARP https://github.com/robotology/yarp/pull/1406#issuecomment-336433473 , but the fact that *nix and Windows use different default settings for YARP_WRAP_STL_STRING make distributing the generated bindings for matlab extremly cumbersome.

**Comment by traversaro** [comment]
Pushed two new commits on the `devel` branch: 
* [ https://github.com/robotology-playground/yarp-matlab-bindings/commit/d9119acca1909261fc9feefe65afa9ba70c2e439 ] Bindings regenerated with the  YARP_WRAP_STL_STRING option set to OFF, the new YARP default on *nix . 
* [ https://github.com/robotology-playground/yarp-matlab-bindings/commit/1a215744e200f5e9a102e2fde363b0ebbca9e593 ] Add CMake check that (hopefully) clearly explains the problem 
This means that from now on if you are using the `devel` branch, you will need to have the `YARP_WRAP_STL_STRING` of YARP set to OFF (the default for new YARP builds on *nix, but on old build and on Windows it is necessary to specify it explicitly).

**Comment by traversaro** [comment]
Solved by the commits mentioned in https://github.com/robotology-playground/yarp-matlab-bindings/issues/15#issuecomment-339272544 , see https://github.com/robotology-playground/yarp-matlab-bindings/issues/17 for more info.

**Comment by diegoferigo** [comment]
Tested, I confirm it works flawlessly now.
