### ISSUE TITLE
Not able to implement a non-blocking read with a buffered port

### ISSUE THREAD

**Issue by GiuliaP** [robotology-playground/yarp-matlab-bindings#2]
I am not able to find an equivalent way of doing this:

BufferedPort<Bottle> p;
Bottle *b = p.read(false);
if (b!=NULL) {
  // data received in *b
}

**Comment by traversaro** [comment]
mhh perhaps wrapping the read method to return a null bottle (i.e. a valid pointer to a null bottle) can solve this issue. Or have you tried if is possible to check if a given yarp object wrapped by swig is pointing to Null?

**Comment by traversaro** [comment]
Hi @GiuliaP , did you solved your issue?

**Comment by GiuliaP** [comment]
Hi @traversaro , 
I saw the issue while on vacation then I forgot: unfortunately, I haven't used the Matlab bindings recently!

**Comment by traversaro** [comment]
Ok, feel free to open a new issue if you face again the problem!
