### ISSUE TITLE
CMake Error could not find automatically Matlab 2018b on macOS 10.14.5

### ISSUE THREAD

**Issue by kouroshD** [robotology-playground/yarp-matlab-bindings#40]
When I checked the option `ROBOTOLOGY_USES_MATLAB` in superbuild, I had the following error (masOS system, macOS 10.14.5).
```
CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY
  Matlab_MEX_EXTENSION Matlab_ROOT_DIR MX_LIBRARY MAIN_PROGRAM) (found
  version "NOTFOUND")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMatlab.cmake:1435 (find_package_handle_standard_args)
  matlab/CMakeLists.txt:96 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/kdarvish/Desktop/icub_ws/robotology-superbuild/build/robotology/yarp-matlab-bindings/CMakeFiles/CMakeOutput.log".
make[2]: *** [robotology/yarp-matlab-bindings/CMakeFiles/YCMStamp/yarp-matlab-bindings-configure] Error 1
make[1]: *** [CMakeFiles/yarp-matlab-bindings.dir/all] Error 2
make: *** [all] Error 2
```
To solve this problem, I add the following environment variable and build again and it worked.
```
export Matlab_ROOT_DIR=$Matlab_ROOT_DIR:$/Applications/MATLAB_R2018b.app
```
cc @gabrielenava @traversaro

**Comment by traversaro** [comment]
We need to either update the vendored `FindMatlab.cmake` file, in particular the variable `MATLAB_VERSIONS_MAPPING` in https://github.com/robotology-playground/yarp-matlab-bindings/blob/master/cmake/FindMatlab.cmake#L231, or specify the missing versions using the `MATLAB_ADDITIONAL_VERSIONS` in the user code, see https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindMatlab.cmake#L243 for the latest version. 
See https://github.com/robotology/blockfactory/blob/master/cmake/FindMatlab.cmake for an example of a project with an updated `FindMatlab.cmake` script.

**Comment by kouroshD** [comment]
So, if we update `MATLAB_VERSIONS_MAPPING` we should do it for all the repos that use matlab. Am I write?

>  specify the missing versions using the MATLAB_ADDITIONAL_VERSIONS in the user code

by `user code`, you mean as an environment variable or inside the CMake file?

**Comment by traversaro** [comment]
> So, if we update MATLAB_VERSIONS_MAPPING we should do it for all the repos that use matlab. Am I write?

Exactly, but some are already updated (see blockfactory).

> by user code, you mean as an environment variable or inside the CMake file?

By user code I mean the CMakeLists.txt file of project, before the call to `find_package(Matlab)`, see the CMake docs at https://cmake.org/cmake/help/v3.12/module/FindMatlab.html#variable:MATLAB_ADDITIONAL_VERSIONS or how it is used in other repos such as https://github.com/helgee/icatt-2016/blob/0fb1012b3639a6d6c53d80cd00b43b72a67b8022/matlab/CMakeLists.txt#L7 .

**Comment by kouroshD** [comment]
@traversaro 
PR
https://github.com/robotology-playground/yarp-matlab-bindings/pull/41
